name: Golang lint, vet and unit test pipeline

on: [push, pull_request]

jobs:
  testmaster:
    name: github (govet, golint and gotest) OSPdO master
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.0 # don't bump this until all operators use 1.18
      - name: Checkout project code
        uses: actions/checkout@v2
        with:
          repository: openstack-k8s-operators/osp-director-operator
      - name: Checkout openstack-k8s-operators-ci project
        uses: actions/checkout@v2
        with:
          path: ./openstack-k8s-operators-ci
      - name: Run govet.sh
        run: ./openstack-k8s-operators-ci/test-runner/govet.sh
      - name: Run golint.sh
        run: ./openstack-k8s-operators-ci/test-runner/golint.sh
      - name: Run gotest.sh
        run: ./openstack-k8s-operators-ci/test-runner/gotest.sh


  teststable: # OSPdO v1.2.x
    name: github (govet, golint and gotest) OSPdO v1.2.x
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0 # don't bump this until we drop OSPdO v1.2.x
      - name: Checkout project code
        uses: actions/checkout@v2
        with:
          repository: openstack-k8s-operators/osp-director-operator
          ref: v1.2.x
      - name: Checkout openstack-k8s-operators-ci project
        uses: actions/checkout@v2
        with:
          path: ./openstack-k8s-operators-ci
      - name: Run govet.sh
        run: ./openstack-k8s-operators-ci/test-runner/govet.sh
      - name: Run golint.sh
        run: ./openstack-k8s-operators-ci/test-runner/golint.sh
      - name: Run gotest.sh
        run: ./openstack-k8s-operators-ci/test-runner/gotest.sh

  testmaster18:
    name: github (govet, golint and gotest) OSPdO master
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Checkout project code
        uses: actions/checkout@v2
        with:
          repository: abays/cinder-operator
          ref: fix_statefulset_patch
      - name: Checkout openstack-k8s-operators-ci project
        uses: actions/checkout@v2
        with:
          path: ./openstack-k8s-operators-ci
      - name: Run govet.sh
        run: ./openstack-k8s-operators-ci/test-runner/govet.sh
      - name: Run golint.sh
        run: ./openstack-k8s-operators-ci/test-runner/golint.sh
      - name: Run gotest.sh
        run: ./openstack-k8s-operators-ci/test-runner/gotest.sh
